name: test_and_build

on:
  push:
    branches: [develop] # PR에서만 동작하도록 삭제 필요
  pull_request:
    branches: [develop]

  workflow_dispatch: # 직접 Actions 탬에서 workflow 실행 가능하도록 설정

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
